カテゴリの追加
imoken777/hackathon-vol9 pull request #17
Opened 2024-07-16 17:55 UTC by s1f10210254

## 内容
メインカテゴリー、サブカテゴリを追加
スクレイピングする際にエリア検索で出なかったらキーワード検索を実行

## 変更点

1. TravelSpotの型情報にcategoriesを追加
2. スクレイピングの際にエリア検索を行っても要素がない場合キーワード検索を実行するようにした

## 関連 Issue

close #14 

## スクリーンショット・動画など

## その他

2024-07-16 23:44 UTC, imoken777 requested changes

2024-07-16 23:44 UTC, imoken777 commented on server/common/types/travelSpots.ts
> +  categories: Record<string, string[]>;
ダミーデータの感じを見るとcategoriesのキーの部分はstringじゃなくてユニオン型で特定の文字列に絞れそうな感じがしたのですがどうでしょうか
例: Record<'観光・遊び'|'グルメ・レストラン'|'それ以外にもあったらここ', string[]>

2024-07-16 23:44 UTC, imoken777 commented on server/domain/travelSpot/service/travelSpotService.ts
> +    const categories: Record<string, string[]> = {};
ここの型はTravelSpotsのcategoriesを使って指定したい
元の型を変更した際にここに気づけない可能性があるため

2024-07-17 05:56 UTC, s1f10210254 commented on server/common/types/travelSpots.ts
> +  categories: Record<string, string[]>;
確かにそっちの方が後々使えそうでいいかも
変更します！

2024-07-17 06:55 UTC, imoken777 commented on server/common/types/travelSpots.ts
> +  categories: Record<string, string[]>;
Recordの第２引数側（ここでいうstring[]）も絞れるならユニオンで絞っておきたいです

2024-07-17 09:18 UTC, imoken777 approved these changes

2024-07-17 09:18 UTC, merged